fields:
    main_menu:
        label: xitara.core::config.main_menu
        type: section
        comment: xitara.core::config.main_menu_comment
    menu_text:
        label: xitara.core::config.menu_text
        type: text
        span: left
        comment: xitara.core::config.menu_text_comment
    compact_display:
        label: xitara.core::config.compact_display
        type: switch
        span: right
        comment: xitara.core::config.compact_display_comment
    menu_icon:
        label: xitara.core::config.menu_icon
        type: mediafinder
        mode: image
        imageWidth: 100
        imageHeight: 100
        span: left
        comment: xitara.core::config.menu_icon_comment
    menu_icon_text:
        label: xitara.core::config.menu_icon_text
        type: text
        span: right
        comment: xitara.core::config.menu_icon_text_comment
        commentHtml: true
